---
title: "Leukemia"
output: 
  ioslides_presentation:
      widescreen: true
author: Emma Ahrensbach Rørbeck (s173733), Julie Maria Johansen (s174595), Simone Majken Stegenborg-Grathwohl (s174596) and Charlotte Würtzen (s174564)
--- 

<style>
.forceBreak { -webkit-column-break-after: always; break-after: column; }
</style>

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE)
library("tidyverse")
library("cowplot")
library("broom")
library("knitr")
load(file = "../data/_raw/golub.RData")
source(file = "../R/99_project_functions.R")
```


## Modelling

Logistic regression

```{r, eval = FALSE, echo = TRUE}
golub_model <- golub_long_nested %>%
  mutate(mdl = map(data, ~glm(type ~ norm_expr_level,
                              data = .x,
                              family = binomial(link = "logit"))))

golub_model <- golub_model %>%
  mutate(mdl_tidy = map(mdl, ~tidy(.x,
                                   conf.int = TRUE))) %>% 
  unnest(mdl_tidy)
```

## Modelling

PCA

```{r, eval = FALSE, echo = TRUE}
pca_fit <- golub_clean_aug %>% 
  select(where(is.numeric),
         -c(type, id)) %>% 
  prcomp(scale = TRUE)
```

## Modelling

PCA

```{r, eval = FALSE, echo = TRUE}
pca_fit <- golub_clean_aug %>% 
  select(where(is.numeric),
         -c(type, id)) %>% 
  prcomp(scale = TRUE)
```

K means analysis

```{r, eval = FALSE, echo = TRUE}
k_type <- golub_clean_aug %>%
  select(-c(type, 
            value, 
            id)) %>%
  kmeans(centers = 2)
```

